### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by sergeykhrykov** [conan-io/wishlist#4]
OpenCV - a major computer vision library.

https://github.com/Itseez/opencv

I would much appreciate libs for Windows and Linux for x86 and x86_64 platforms!

**Comment by memsharded** [comment]
I've done OpenCV in the past, and I love it. I will make a proposal, and keep you updated.

**Comment by memsharded** [comment]
I have done an initial setup, the github repo for the package recipe will be: https://github.com/memsharded/conan-opencv

I have been able to create a package binary for MSVC 14, and build a consumer app, but still very preliminary, and it didnt launch because of missing dlls, but just in case anybody want to start having a look to the recipe. Nothing uploaded to conan yet, just working locally, but you can clone the repo and "conan export" it to your local conan cache to start playing with it.

I am focusing on OpenCV 2.4.13, OpenCV 3 shouldn`t be very difficult, except the split into two separate repositories, (main and contrib). Are you fine with this version?

**Comment by memsharded** [comment]
Ok, first examples working! Both static and shared versions of OpenCV 2.4.13, in Windows, MSVC14 (might work with previous versions too).

There are some instructions in Readme: https://github.com/memsharded/conan-opencv.

I have added a package-test, which uses haar detection of face and eyes. If the package fails for your use case, it would be great if you could add a main.cpp inside the test_package, so I can use them to check the package correctness too.

Testers and feedback appreciated. Please submit package bug/issues to the package repository, not here. Here, just comments, validations, and feedback. Thanks!

**Comment by sergeykhrykov** [comment]
Thank you!
I'll post my experience with your package as soon I try it.

**Comment by memsharded** [comment]
Great, thank you! Looking forward to hearing your feedback, and I will move this package forward (add linux, OSX, probably use the TBB conan package...)

**Comment by Phibedy** [comment]
Hi, I just wondered what have to be done to add linux support as I would need opencv :)

**Comment by memsharded** [comment]
Ok, I stopped development of this package because of not receiving feedback, but if you needed I will push it again, and tell you for testing. Thanks!

**Comment by memsharded** [comment]
Working in Win & Ubuntu. Not uploaded yet, please test from repo, that would be the best to collaborate and iterate it:

```bash
$ git clone https://github.com/memsharded/conan-opencv
$ cd conan-opencv
$ conan test_package
```
A window with face detection of a very well known image should pop up if successful

I have added system_requirements for gtk2, probably not really necessary for some cases, but widely used. We could use options later to configure those things, but I think better have a working package as start point.

Please feedback!

**Comment by Phibedy** [comment]
Not working on Ubuntu 14.04 LTS, thank you for support :)
Do I have to update conan/use some other version?
```
phibedy@phibedy--T530:~/Documents/programming/c++/lms_conan/conan-opencv$ conan test_package
Exporting package recipe
OpenCV/2.4.13@memsharded/testing: A new conanfile.py version was exported
OpenCV/2.4.13@memsharded/testing: Folder: /home/phibedy/.conan/data/OpenCV/2.4.13/memsharded/testing/export
Requirements
    OpenCV/2.4.13@memsharded/testing from local
Packages
    OpenCV/2.4.13@memsharded/testing:de9c231f84c85def9df09875e1785a1319fa8cb6

ERROR: OpenCV/2.4.13@memsharded/testing: Error in package_info() method, line 75
	other_libs = self.collect_libs()
	'OpenCVConan' object has no attribute 'collect_libs'
```

**Comment by memsharded** [comment]
Yes, please, upgrade conan to 0.13.1, it implements the new ``collect_libs`` functionality.

**Comment by Phibedy** [comment]
@memsharded great work, thank you :)
I don't want to be rude, but opencv 3 would be awesome, as I have some code that depends on it

**Comment by memsharded** [comment]
So, did it work in Ubuntu 14.04?
No rude at all, this is what this wishlist is for :)
Ok, I'll put opencv3 to the backlog too. Would you need just the core OpenCV libraries or also libraries from the contrib repository?

**Comment by Phibedy** [comment]
Also from the contrib repository,
thank you :)

**Comment by masaeedu** [comment]
@memsharded Is the correct approach for using this package to add the opencv dll folder in the conan cache to our PATH manually? I was having trouble getting stuff to run with both the cmake and Visual Studio generators, and finally figured out that I needed to add the bin folder to my PATH.

**Comment by lasote** [comment]
@masaeedu definitely not the correct approach. You could use the "imports" feature to copy the DLL's to your project build folder. http://conanio.readthedocs.io/en/latest/manage_deps/conanfile_txt.html?highlight=imports#imports

If you don't like maybe @memsharded can add PATH to env_info to "change" the path with a virtual environment generator. http://conanio.readthedocs.io/en/latest/integrations/virtualenv.html?highlight=virtual%20environment

**Comment by masaeedu** [comment]
@lasote Sorry, it turns out I was even more confused than is apparent from that comment. I was actually using *your* opencv package with the Visual Studio generator, and was having trouble with the linker. If I add `bin, *.dll -> ./bin` under `[imports]`, it copies the dll to a `bin` folder adjacent to the conanbuildinfo.props file, but I still have to add that folder manually to my path. 

If the generator could also do the Visual Studio equivalent of adding that folder to target_link_libraries in CMakeLists.txt, that would be ideal. That way I just need to set and forget `bin, *.dll -> ./bin` under `[imports]` and everything would just work.

**Comment by lasote** [comment]
@masaeedu Due it's related to a conan generator, please, open an issue at https://github.com/conan-io/conan repository detailing your use case and problem. Thanks!

**Comment by helmesjo** [comment]
Awfully quiet in here... :) What is the current state? Searched around a bit but couldn't find any OpenCV conan-package.

**Comment by memsharded** [comment]
Indeed https://github.com/conan-community/conan-opencv is the current work. It already builds with transitive dependencies of image libraries from the bincrafters repo. Those libraries will be soon in conan-center, and hopefully a release of OpenCV package will follow after that.

**Comment by helmesjo** [comment]
Ah alright, sounds great!
Thanks!

**Comment by Croydon** [comment]
All of the Conan dependencies are in conan-center

**Comment by SSE4** [comment]
finally, in conan-centre: https://bintray.com/conan-community/conan/opencv%3Aconan

**Comment by Croydon** [comment]
https://bintray.com/conan/conan-center?filterByPkgName=opencv 👍

**Comment by uilianries** [comment]
![](https://media.giphy.com/media/GStLeae4F7VIs/giphy.gif)

**Comment by theirix** [comment]
Aaand.... 4.0 [is out today](https://opencv.org/opencv-4-0-0.html)! :)

**Comment by uilianries** [comment]
![](https://assets.pando.com/uploads/2012/06/picard-facepalm-2.jpg)

**Comment by SSE4** [comment]
never mind, 4.0.0 binaries are also available on conan

**Comment by danimtb** [comment]
WOW!! Kudos for the impressive job @SSE4 🥇

**Comment by SSE4** [comment]
@beco81 there is an option for contrib, just use something like `conan install opencv/3.4.2@conan/stable -o opencv:contrib=True`

**Comment by beco81** [comment]
Thanks, I've tried it, but got an error:

`ERROR: Missing prebuilt package for 'opencv/3.4.3@conan/stable'
Try to build it from sources with "--build opencv"`

If I try to run it with --build I get an other error:

`opencv/3.4.3@conan/stable: ERROR: Unable to remove source folder C:\.conan\2d9m1p1c\1
Cannot change permissions for C:\.conan\2d9m1p1c\1\3.4.3.zip! Exception info: (<class 'PermissionError'>, PermissionError(13, 'Zugriff verweigert'), <traceback object at 0x0000025E4952EC08>)
opencv/3.4.3@conan/stable: WARN: **** Please delete it manually ****
ERROR: opencv/3.4.3@conan/stable: Error in source() method, line 42
        tools.get("https://github.com/opencv/opencv/archive/%s.zip" % self.version)
        PermissionError: [WinError 5] Zugriff verweigert: '3.4.3.zip'`

If I delete the folder manually and retry it, I get the same. I'm on Windows and running the comand windows as an Administrator.

**Comment by SSE4** [comment]
@beco81 that's wierd - may it's anti-virus software or Windows indexing service? I've also seen similar issues with TortoiseSVN/TortoiseGIT.

**Comment by beco81** [comment]
After spending several hours with this issue I'll summarize my findings. It still does not work on my company laptop, I've tried the fllowings:
- Disabled indexing service
- Disabled antivirus SW
- Removed Tortoise SVN/Git

It fails with the same problem whatever I try, regardless of I am logged in as an administrator or user, running it from windows cmd or MinGW. It runs fine however without touching any settings on my private computer at home, and also on one of my colleagues' laptop wtih similar settings as mine has.
Now I don't think any external tool could block it by holding a reference to the zip file, I am always able to delete it manually. Even I tried right after a build failure to start python and run os.unlink() (that's what tools.get() does), it worked. After checking the code I think that at OS level the zip file may not be released immediately after leaving the "with" statement in unzip(), so the file is still locked when unlink() is called. Of course it's just a guess, I can't prove it.
Anyway, this is a blocker issue for me now, and I'd like to find a solution. I still like conan and I'd like to get my team start using it, but OpenCV is one of the major libraries we depend on. For the core libs the prebuilt packages are fine, but I don't want to mix them with some self-built contrib packages. So my questions are:
- Would it be possible to add prebuilt-packages for the contrib as well? This won't solve my root problem, but can be a workaround.
- Is it possible to copy some built packages from one system to another?
- I find it too strict to break the build when deleting a temporary zip file fails. The tools.get() call should be able to tolerate this, and sign by a warning to remove it manually. Can you agree with this? I'm thinking of creating a ticket for it on conan github.

**Comment by danimtb** [comment]
Hi @beco81,

I think it is better if report your issue in the issue tracker of conan-community repo https://github.com/conan-community/community/issues that way we can follow it in detail and find a way to fix it together.

Thanks!
